import { defineConfig } from '@rsbuild/core';
import { rspack } from '@rspack/core';
import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';

// https://rsbuild.dev/plugins/list/plugin-react
import { pluginReact } from '@rsbuild/plugin-react';

// https://rsbuild.dev/plugins/list/plugin-svgr
import { pluginSvgr } from '@rsbuild/plugin-svgr';

// https://github.com/rspack-contrib/rsbuild-plugin-styled-components
import { pluginStyledComponents } from '@rsbuild/plugin-styled-components';

export default defineConfig({
  plugins: [
    pluginReact({
      reactRefreshOptions: {
        exclude: [/[\\/]node_modules[\\/]/, /\.css\.ts$/],
      },
    }),
    pluginSvgr(),
    pluginStyledComponents({ displayName: true }),
  ],

  tools: {
    rspack: {
      experiments: {
        css: true,
      },
      plugins: [new VanillaExtractPlugin()],
      module: {
        rules: [
          {
            test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
            use: [
              rspack.CssExtractRspackPlugin.loader,
              {
                loader: 'css-loader',
                options: {
                  url: false, // Required as image imports should be handled via JS/TS import statements
                },
              },
            ],
          },
        ],
      },
    },
  },
});
